### ISSUE TITLE
Got a runtime error when running

### ISSUE THREAD

**Issue by lstep** [hgsigner/gootstrap#1]
When trying to execute gootstrap on an Ubuntu Linux:
```
# gootstrap new foo
===> Creating package foo
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x49b8ab]

goroutine 1 [running]:
text/template.(*Template).ExecuteTemplate(0x0, 0x7f9690c97670, 0xc820284fc0, 0x5bea10, 0xe, 0x0, 0x0, 0x0, 0x0)
	/home/lstep/.go/src/text/template/exec.go:117 +0x3b
main.GitIgnoreFile.Parse(0x0, 0x0)
	/home/lstep/go/src/github.com/hgsigner/gootstrap/templates.go:25 +0xc4
main.(*GitIgnoreFile).Parse(0x6c4cd0, 0x0, 0x0)
	<autogenerated>:7 +0x9a
main.gootFile.createFile(0x5bea00, 0x9, 0x0, 0x0, 0xc820010530, 0xe, 0x5ddfe0, 0x1d, 0x0, 0x0, ...)
	/home/lstep/go/src/github.com/hgsigner/gootstrap/goot_file.go:69 +0xda
main.createOrErrorOut(0x5bea00, 0x9, 0x0, 0x0, 0xc820010530, 0xe, 0x5ddfe0, 0x1d, 0x0, 0x0, ...)
	/home/lstep/go/src/github.com/hgsigner/gootstrap/goot_file.go:106 +0x3d
main.gootFile.performCreation(0x5bea00, 0x9, 0x0, 0x0, 0xc820010530, 0xe, 0x5ddfe0, 0x1d, 0x0, 0x0, ...)
	/home/lstep/go/src/github.com/hgsigner/gootstrap/goot_file.go:85 +0x6c
main.filesList.Process(0xc8200ab9b0, 0x8, 0x8, 0x0, 0x0)
	/home/lstep/go/src/github.com/hgsigner/gootstrap/goot_file.go:23 +0xd6
main.createPackage(0x7ffc7df0c287, 0x3, 0x0, 0x0, 0x7f9690c97210, 0xc820034010)
	/home/lstep/go/src/github.com/hgsigner/gootstrap/gootstrap.go:155 +0x1f77
main.runCommand(0xc82000a2d0, 0x3, 0x3, 0x7f9690c97210, 0xc820034010)
	/home/lstep/go/src/github.com/hgsigner/gootstrap/gootstrap.go:61 +0x47f
main.run(0xc82000a2d0, 0x3, 0x3, 0x7f9690c97210, 0xc820034010)
	/home/lstep/go/src/github.com/hgsigner/gootstrap/gootstrap.go:28 +0x268
main.main()
	/home/lstep/go/src/github.com/hgsigner/gootstrap/gootstrap.go:70 +0x68

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/lstep/.go/src/runtime/asm_amd64.s:1696 +0x1
```
Version :
```
# go version
go version go1.5.1 linux/amd64
```

**Comment by Cheesestring13** [comment]
I'm getting the same:

```
$ gootstrap new foo
===> Creating package foo
===> Creating directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x9bc1b]

goroutine 1 [running]:
text/template.(*Template).ExecuteTemplate(0x0, 0x660568, 0xc820478310, 0x1bd900, 0xe, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.1/libexec/src/text/template/exec.go:117 +0x3b
main.GitIgnoreFile.Parse(0x0, 0x0)
    /Users/jstringer/Go/src/github.com/hgsigner/gootstrap/templates.go:25 +0xc4
main.(*GitIgnoreFile).Parse(0x2c3648, 0x0, 0x0)
    <autogenerated>:7 +0x9a
main.gootFile.createFile(0x1bd8f0, 0x9, 0x0, 0x0, 0xc8200ba000, 0x13, 0x1dc560, 0x1d, 0x0, 0x0, ...)
    /Users/jstringer/Go/src/github.com/hgsigner/gootstrap/goot_file.go:69 +0xda
main.createOrErrorOut(0x1bd8f0, 0x9, 0x0, 0x0, 0xc8200ba000, 0x13, 0x1dc560, 0x1d, 0x0, 0x0, ...)
    /Users/jstringer/Go/src/github.com/hgsigner/gootstrap/goot_file.go:106 +0x3d
main.gootFile.performCreation(0x1bd8f0, 0x9, 0x0, 0x0, 0xc8200ba000, 0x13, 0x1dc560, 0x1d, 0x0, 0x0, ...)
    /Users/jstringer/Go/src/github.com/hgsigner/gootstrap/goot_file.go:85 +0x6c
main.filesList.Process(0xc8200b59b0, 0x8, 0x8, 0x0, 0x0)
    /Users/jstringer/Go/src/github.com/hgsigner/gootstrap/goot_file.go:23 +0xd6
main.createPackage(0x7fff5fbff526, 0x8, 0x0, 0x0, 0x3c11e8, 0xc820084008)
    /Users/jstringer/Go/src/github.com/hgsigner/gootstrap/gootstrap.go:155 +0x1f77
main.runCommand(0xc820078120, 0x3, 0x3, 0x3c11e8, 0xc820084008)
    /Users/jstringer/Go/src/github.com/hgsigner/gootstrap/gootstrap.go:61 +0x47f
main.run(0xc820078120, 0x3, 0x3, 0x3c11e8, 0xc820084008)
    /Users/jstringer/Go/src/github.com/hgsigner/gootstrap/gootstrap.go:28 +0x268
main.main()
    /Users/jstringer/Go/src/github.com/hgsigner/gootstrap/gootstrap.go:70 +0x68

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1
```

```
$ go version
go version go1.5.1 darwin/amd64
```

**Comment by hgsigner** [comment]
Hi guys,
I'm going to check what could be wrong here.
Thanks for the feedback.

**Comment by klauern** [comment]
Just to cover all bases, I, too got this error on Windows:

```powershell
C:\dev\golang\src\github.com\klauern
λ gootstrap new project_Name
===> Creating package project_Name
===> Creating directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x4a0222]

goroutine 1 [running]:
text/template.(*Template).ExecuteTemplate(0x0, 0x828e28, 0xc08245c690, 0x5d8070, 0xe, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/text/template/exec.go:117 +0x42
main.GitIgnoreFile.Parse(0x0, 0x0)
        C:/dev/golang/src/github.com/hgsigner/gootstrap/templates.go:25 +0xcb
main.(*GitIgnoreFile).Parse(0x6e3728, 0x0, 0x0)
        <autogenerated>:7 +0xa1
main.gootFile.createFile(0x5d8060, 0x9, 0x0, 0x0, 0xc08200aec0, 0x17, 0x5f7f00, 0x1d, 0x0, 0x0, ...)
        C:/dev/golang/src/github.com/hgsigner/gootstrap/goot_file.go:69 +0xe1
main.createOrErrorOut(0x5d8060, 0x9, 0x0, 0x0, 0xc08200aec0, 0x17, 0x5f7f00, 0x1d, 0x0, 0x0, ...)
        C:/dev/golang/src/github.com/hgsigner/gootstrap/goot_file.go:106 +0x44
main.gootFile.performCreation(0x5d8060, 0x9, 0x0, 0x0, 0xc08200aec0, 0x17, 0x5f7f00, 0x1d, 0x0, 0x0, ...)
        C:/dev/golang/src/github.com/hgsigner/gootstrap/goot_file.go:85 +0x73
main.filesList.Process(0xc0820359b0, 0x8, 0x8, 0x0, 0x0)
        C:/dev/golang/src/github.com/hgsigner/gootstrap/goot_file.go:23 +0xdd
main.createPackage(0xc082004290, 0xc, 0x0, 0x0, 0x824210, 0xc08202a010)
        C:/dev/golang/src/github.com/hgsigner/gootstrap/gootstrap.go:155 +0x1f7e
main.runCommand(0xc0820380c0, 0x3, 0x3, 0x824210, 0xc08202a010)
        C:/dev/golang/src/github.com/hgsigner/gootstrap/gootstrap.go:61 +0x486
main.run(0xc0820380c0, 0x3, 0x3, 0x824210, 0xc08202a010)
        C:/dev/golang/src/github.com/hgsigner/gootstrap/gootstrap.go:28 +0x26f
main.main()
        C:/dev/golang/src/github.com/hgsigner/gootstrap/gootstrap.go:70 +0x6f
```

```powershell
C:\dev\golang\src\github.com\klauern
λ go version
go version go1.5.1 windows/amd64
```

**Comment by hgsigner** [comment]
I'm running some tests here. On my mac it runs with no problem :/ Trying to figure out what is the problem.

**Comment by hgsigner** [comment]
The problem is the path of the templates here `template.ParseGlob("./templates/*.tmpl")`
I'm fixing it.

**Comment by hgsigner** [comment]
Just fixed it. Would you guys `go get` again to check if it works?

**Comment by klauern** [comment]
It works for me now.  Thank you
